CREATE DATABASE LIVRARIA;
USE LIVRARIA;
CREATE TABLE LIVRO (
	NOME_DO_LIVRO VARCHAR(100),
	NOME_DO_AUTOR VARCHAR(100),
	SEXO_DO_AUTOR CHAR(1),
	NUMERO_DE_PAGINAS INT(5),
	NOME_DA_EDITORA VARCHAR(30),
	VALOR_DO_LIVRO FLOAT(10,2),    /* 10 CASAS ONDE 2 SÃO DECIMAIS */
	UF_DA_EDITORA CHAR(2),
	ANO_DA_PUBLICACAO CHAR(4)
);

/* INSERT INTO TABELA */
INSERT INTO LIVRO (NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO_DO_AUTOR, NUMERO_DE_PAGINAS, NOME_DA_EDITORA, VALOR_DO_LIVRO, UF_DA_EDITORA, ANO_DA_PUBLICACAO)
		VALUES ('País dos Pitigrundos', 'Cláudia Dalla', 'F', 60, 'Literatura e Arte', 6.00, 'RJ', 1998);
INSERT INTO LIVRO (NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO_DO_AUTOR, NUMERO_DE_PAGINAS, NOME_DA_EDITORA, VALOR_DO_LIVRO, UF_DA_EDITORA, ANO_DA_PUBLICACAO)
		VALUES ('O fim da vila', 'Robert Romeu', 'M', 98, 'Vulcão', 45.00, 'SP', 1990);
INSERT INTO LIVRO (NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO_DO_AUTOR, NUMERO_DE_PAGINAS, NOME_DA_EDITORA, VALOR_DO_LIVRO, UF_DA_EDITORA, ANO_DA_PUBLICACAO)
		VALUES ('Sem lutas', 'Carlos Rocha', 'M', 134, 'Vulcão', 50.00, 'SP', 1980);
INSERT INTO LIVRO (NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO_DO_AUTOR, NUMERO_DE_PAGINAS, NOME_DA_EDITORA, VALOR_DO_LIVRO, UF_DA_EDITORA, ANO_DA_PUBLICACAO)
		VALUES ('Coração duro', 'Damião Rocha', 'M', 164, 'Literatura e Arte', 50.00, 'RJ', 1980);
INSERT INTO LIVRO (NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO_DO_AUTOR, NUMERO_DE_PAGINAS, NOME_DA_EDITORA, VALOR_DO_LIVRO, UF_DA_EDITORA, ANO_DA_PUBLICACAO)
		VALUES ('O escudeiro do rei', 'Amanda Nanda', 'F', 201, 'Montanhas', 40.00, 'MG', 1960);
		
/* TRAZER TODOS OS DADOS */
SELECT NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO_DO_AUTOR, NUMERO_DE_PAGINAS, NOME_DA_EDITORA, VALOR_DO_LIVRO, UF_DA_EDITORA, ANO_DA_PUBLICACAO FROM LIVRO;
		
/* TRAZER O NOME DO LIVRO E O NOME DA EDITORA */
SELECT NOME_DO_LIVRO, UF_DA_EDITORA FROM LIVRO;

/*TRAZER O NOME DO LIVRO E A UF DOS LIVROS PUBLICADOS POR AUTORES DO SEXO MASCULINO*/
SELECT NOME_DO_LIVRO, UF_DA_EDITORA FROM LIVRO
WHERE SEXO_DO_AUTOR = 'M';

/*TRAZER O NOME DO LIVRO E O NUMERO DE PAGINAS DOS LIVROS PUBLICADOS POR AUTORES DO SEXO FEMININO*/
SELECT NOME_DO_LIVRO, NUMERO_DE_PAGINAS FROM LIVRO
WHERE SEXO_DO_AUTOR = 'F';

/*TRAZER OS VALORES DOS LIVROS DAS EDITORAS DE SÃO PAULO*/
SELECT VALOR_DO_LIVRO
WHERE UF_DA_EDITORA LIKE 'SP';

/*TRAZER OS DADOS DOS AUTORES DO SEXO MASCULINO QUE TIVERAM LIVROS PUBLICADOS POR SP OU RJ*/
SELECT NOME_DO_AUTOR, SEXO_DO_AUTOR 
FROM LIVRO
WHERE SEXO_DO_AUTOR = 'M'
AND (UF_DA_EDITORA = 'SP'
OR UF_DA_EDITORA = 'RJ');
